config/routes.rb
Rails.application.routes.draw do
  resources :boards

  resources :sounds, only: [:index, :create]

  post "/boards/add_sounds" => "boards#add_sounds", as: :add_sounds
end

app/models/board.rb
class Board < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true

	has_many :board_sounds
	has_many :sounds, through: :board_sounds
end


# stock_prices_yesterday  = [10, 7, 5, 8, 11, 9, 2]
stock_prices_yesterday  = [5, 3, 2]

def best_profit(stock_prices)
  lowest_price = stock_prices[0]
  best_profit = 0
  stock_prices.each_with_index do |current_price, idx|
    if current_price < lowest_price
      lowest_price = price
    end

    current_profit = current_price - lowest_price
    if current_profit > best_profit
      best_profit = current_profit
    end
  end

  best_profit > 0 ? best_profit : 'No profits today!'
end

app/models/board_sound.rb
class BoardSound < ActiveRecord::Base
	validates :board_id, uniqueness: { 
    scope: :sound_id, 
    message: "Sound has already been added to Board"
  }

	belongs_to :board
	belongs_to :sound
end

app/models/sound.rb
class Sound < ActiveRecord::Base
  validates :name, uniqueness: true

	has_many :board_sounds
	has_many :boards, through: :board_sounds

  def self.dedupe
    # find all models and group them on keys which should be common
    grouped = all.group_by{|model| [model.name] }
    grouped.values.each do |duplicates|
      # the first one we want to keep right?
      first_one = duplicates.shift # or pop for last one
      # if there are any more left, they are duplicates
      # so delete all of them
      duplicates.each{|double| double.destroy} # duplicates can now be destroyed
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
	def index
		@boards = Board.all
	end

	def show
		@board = Board.find(params[:id])
		@sounds = @board.sounds
	end

	def new
		@board = Board.new
	end

	def edit
		@board = Board.find(params[:id])
	end

	def add_sounds
		
		@board = Board.find(params[:board_id])


		board_sound = BoardSound.new(board_id: @board.id, sound_id: params[:board][:sound_ids])
		# params[:board][:sound_ids].each do |sound_id|
		# 	byebug
		# 	continue if sound_id.empty?
			
		# 	board_sound = BoardSound.new(board_id: @board.id, sound_id: sound_id)
		# 	if not board_sound.save
		# 		errors << 
		# 	end
		# end
		
		redirect_to :show
	end

	def create
		@board = Board.new(board_params)

		if @board.save
			redirect_to @board
		else
			render :new
		end
	end

	def update
		@board = Board.find(params[:id])
		

		if @board.update(board_params)
			redirect_to @board
		else
			render :edit
		end
	end

	def destroy
		@board = Board.find(params[:id])
		@board.destroy

		redirect_to boards_path
	end

	private

	def board_params
		params.require(:board).permit(:name)
	end
end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController

  def index

  	board_sound_ids = Board.find(params[:board_id]).sounds.pluck(:id)
    @sounds = Sound.where("lower(name) like ? and id not in (?)", "%" + params[:search_str].downcase + "%",   board_sound_ids)
    .limit(5)

		@sounds = @sounds.map.with_index{ |sound, i| { 
			'$order': i+1, 
			value: sound.id, 
			text: sound.name,
			description: sound.description
			}
		}
    render json: @sounds
  end

	def create
		@sound = Sound.new(sound_params)
		if @sound.save
			render json: @sound
		else
			render json: { errors: @sound.errors.full_messages }, :status => 422
		end
	end

	def destroy
		@sound = Sound.find(params[:id])
		@sound.destroy
		redirect_to boards_path
	end

	private

	def sound_params
		params.require(:sound).permit(:name, :description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_for @board do |f| %>
	<% if @board.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@board.errors.count, "error") %> prohibited
				this board from being saved:
			</h2>
			<ul>
				<% @board.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/boards/edit.html.erb
<h1><%= link_to 'Edit Board', board_path(@board) %></h1>

<%= render 'form' %>

<%= link_to 'Back to Boards', boards_path %>

app/views/boards/index.html.erb
<h1>Boards</h1>
<table>
  <th>
    <td>
      Name
    </td>
  </th>
  <% @boards.each do |board| %>
  <tr>
    <td>
      <%= link_to board.name, board_path(board) %>
    </td>
    <td>
      <%= link_to 'edit', edit_board_path(board) %>
    </td>
    <td>
      <%= link_to 'delete', board_path(board), method: 'delete', 
      data: {
        confirm: "are you sure you want to delete"
        } %>
    </td>
  </tr>
  <% end %>
</table>
  
<%= link_to 'Create A New Board', new_board_path %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form' %>

<%= link_to 'Back to Boards', boards_path %>

app/views/boards/show.html.erb
<div class="container board">  
  
  <div class="row board__header">
    <div class="board__title">
      <span><%= link_to @board.name, edit_board_path(@board) %></span>
    </div>

    <div class="board__search">
      <%= form_for @board, :url => url_for(action: 'add_sounds', controller: 'boards'), :method => 'POST' do |f| %>
        <div class="form-group">
          <%= f.select :sound_ids, [[]], {}, 
          {multiple: false, class: "selectize"} %>
          <%= hidden_field_tag(:board_id, @board.id) %>

          <%= f.submit 'Add Sound', class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
  
  <div class="row board__content">
    <% @sounds.each do |sound| %>
      <button type="button" class="btn btn-warning board__sound-button">
        <%= sound.name %>
      </button>
    <% end %>
  </div>
  
  <div class="row baord__footer">
    <div></div>
  </div>
</div>

<%= render :partial => 'sounds/modal' %>

<%= link_to 'Back to Boards', boards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Soundboard</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/boards/">
        <p class="navbar-text" style="margin-top: 0px; margin-right: 5px;">
	        <%= image_tag("starcow.png", size: "30x30")%>
	        SoundBoard
        </p>
      </a>
    </div>
  </div>
</nav>
<%= yield %>

</body>
</html>

app/views/sounds/_form.html.erb
<%= form_for Sound.new do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary new-sound-btn" %>
  </div>
<% end %>

app/views/sounds/_modal.html.erb
<div class="modal fade sound-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Create Sound</h4>
      </div>
      <div class="modal-body">
        <%= render :partial => 'sounds/form' %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->